[package]
name = "afarray"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license-file = "LICENSE"
description = "Convenience methods for working with ArrayFire arrays in Rust"
repository = "http://github.com/haydnv/collate"
readme = "README.md"

categories = ["algorithms", "data-structures", "hardware-support", "mathematics", "rust-patterns"]
keywords = ["array", "arrayfire", "gpu", "ndarray", "tensor"]

[dependencies]
# There is a bug in ArrayFire 3.7 which breaks af::any and af::all. It should be fixed in ArrayFire 3.8.
arrayfire = "<3.7"
number-general = {path = "../number-general"}
num = "0.2"
safecast = "0.1"
