[package]
name = "afarray"
version = "0.2.0"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"
description = "Convenience methods for working with ArrayFire arrays in Rust"
repository = "http://github.com/haydnv/collate"
readme = "README.md"

categories = ["algorithms", "data-structures", "hardware-support", "mathematics", "rust-patterns"]
keywords = ["array", "arrayfire", "gpu", "ndarray", "tensor"]

[build-dependencies]
pkg-config = "0.3"

[dependencies]
arrayfire = "3.8"
bincode = "1.3"
number-general = "0.3"
num-complex = "0.2"
safecast = "0.1"
serde = "1.0"
